version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      DOCKER_ENV: "true"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: us-east-1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5001
    ports:
      - "3000:80"
    depends_on:
      - backend
